config/routes.rb
Miles::Application.routes.draw do

  match "/queue" => DelayedJobWeb, :anchor => false

  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/i do

    get 'archives_count', as: :archive_count, :to => "stitches#archives_count"

    resources :brands do
      collection do
        get 'count'
      end
    end

    resources :stitch_type_products do
      collection do
        get 'count'
      end
    end

    resources :suppliers do
      collection do
        get 'count'
      end
    end

    resources :macro_seasons do
      collection do
        get 'count'
      end
    end

    resources :stitches do
      collection do
        get 'archive', as: :archive
        get 'count'
      end

      resources :pictures, :only => [:index, :show]

    end

    resources :pictures do
      collection do
        get 'download_url', :as => "download_archive"
        get 'export'
        get 'count'
      end
    end

    resources :stitch_products do
      collection do
        get 'count'
      end
    end

    resources :yarns do
      collection do
        get 'count'
      end
    end

    resources :products do
      collection do
        get 'count'
      end
    end

    resources :machines do
      collection do
        get 'count'
      end
    end

    resources :stitch_types do

      member do
        resources :stitch_type_products, :only => [:show, :index]
      end

      collection do
        get 'count'
        get 'tree'
      end
    end
    root :to => 'stitches#index'
  end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  match '*path', to: redirect {|params, request| "/#{I18n.default_locale}#{request.original_fullpath}"}, constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

end

app/models/stitch.rb
class Stitch < I18nModel
  attr_accessible :brand_id, :composition, :description, :machine_id, :season_code, :stretch, :thinness
  attr_accessible :vanise, :year, :code, :yarn_codes, :product_codes, :stitch_type_codes, :stitch_type_id
  attr_accessible :updated_images, :supplier_codes

  translates :description, :composition

  belongs_to :machine
  belongs_to :brand
  belongs_to :stitch_type

  belongs_to :macro_season, :foreign_key => :season_code, :primary_key => :code

  has_many :stitch_products
  has_many :products, :through => :stitch_products
  has_many :pictures

  has_many :stitch_yarns
  has_many :yarns, :through => :stitch_yarns

  scope :updated, lambda{|updated_val|
    if updated_val
      {:conditions => ["stitches.updated_images = ?",true]}
    else
      {}
    end
  }

  scope :with_type , lambda{ |stitch_type_id|
    if stitch_type_id.blank?
      {}
    else
      {:conditions => ["stitches.stitch_type_id = ?",stitch_type_id.to_i]}
    end
  }

  scope :filterd_by_code, lambda{ |filter_code|
    if filter_code.blank?
      {}
    else
      {:conditions => ["stitches.code = ?",filter_code]}
    end
  }

  def self.with_code(code)
    self.all(:conditions => {:code => code}, :limit => 1).first
  end

  def yarn
    self.yarns.first if self.yarns.any?
  end

  def name
    self.description
  end

end

app/models/stitch_type.rb
class StitchType < I18nModel
  attr_accessible :description, :full_description, :leaf, :parent_id, :code
  translates :description, :full_description

  #has_ancestry
  has_many :stitches
  has_many :childrens, :class_name => 'StitchType', :foreign_key => :parent_id, :primary_key => :id
  has_many :stitch_type_products
  has_many :products, :through => :stitch_type_products
  has_many :stitch_type_translations, :class_name => 'StitchType::Translation'

  belongs_to :parent, :class_name => 'StitchType', :foreign_key => :parent_id

  def self.with_code(code)
    self.all(:conditions => {:code => code.to_s}, :limit => 1).first
  end

  def name
  	self.description
  end

  def entry_type
  	"node"
  end

  def has_children?
    self.childrens.size > 0
  end

  def has_products?
    self.stitch_type_products.size > 0
  end

  scope :with_parent , lambda{ |parent_id|
    if parent_id.blank?
      {}
    elsif (parent_id != '-1')
      {:conditions => ["stitch_types.parent_id = ?",parent_id.to_i]}
    else
      {:conditions => ["stitch_types.parent_id IS NULL"]}
    end
  }



end

app/controllers/stitches_controller.rb
class StitchesController < ApplicationController

  before_filter :set_pagination, :only => [:index]

  # GET /stitches
  # GET /stitches.json
  def index
    @stitches = Stitch.paginate(:page => @__page, :per_page => @__limit).includes(:pictures)
      .updated(params[:updated].present?)
      .filterd_by_code(params[:code])
      .with_type(params[:stitch_type_id])
      .with_translations(Globalize.locale)
      .order("stitches.id ASC")

    x = {
      :source => "webapp",
      :user => "guest",
      :code => "",
      :year => "",
      :composition => "",
      :season_code => "",
      :stitch_type_codes => "",
      :supplier_codes => "",
      :yarn_codes => "",
      :product_codes => "",
      :brand_code => "",
      :machine_id => "",
      :thinness => "",
      :stretch => "",
      :vanise => "",
      :page => "1",
      :limit => "100",
      :locale => "it"
    }

    respond_to do |format|
      format.html # index.html.erb
      format.json #{ render json: @stitches }
    end
  end

  def archive

    kind =  (params[:kind].nil? || !["all_stitches",
                                    "updated_stitches",
                                    "all_products_images",
                                    "all_products_sketches",
                                    "updated_products_images",
                                    "updated_products_sketches",
                                    "backup",
                                    "backup_test"].include?(params[:kind]) ? "updated_stitches" : params[:kind])

    if Delayed::Job.count == 0
      Archive.delay.call_rake "archive:#{kind}"
      flash[:notice] = 'Procedure started in background'
    else
      flash[:warning] = 'Background procedure/s already running, please wait until completed'
    end

    respond_to do |format|
      format.html do
        redirect_to request.referer.nil? ? root_url : request.referer
      end
      format.json { render json: {:error => "Job started"}}
    end

  end

  def archives_count

    @count = 0
    base_path = Rails.env.development? ? Rails.root.join("public","system") : "/media/milnas01"
    directory = File.expand_path("#{base_path}/archives/")
    archives = ["stitches_images","products_images","products_sketches"]

    if params[:archive].blank? || !archives.index(params[:archive])

      respond_to do |format|
        format.html do
          flash[:warning] = "Invalid archive type"
          redirect_to root_url
        end
        format.json { render json: {:error => "Invalid archive type"}}
      end
      return
    end

    human_name = params[:archive].gsub("_"," ").capitalize

    Dir[File.join(directory, "#{params[:archive]}*.zip")].each do |file|
      @count +=1
    end

    respond_to do |format|
      format.html do
        flash[:notice] = "#{human_name} are splitted into #{@count} archives"
        redirect_to root_url
      end
      format.json { render json: {:count => @count}}
    end

  end



  def count
    @count = Stitch.count

    respond_to do |format|
      format.html do
        flash[:warning] = 'Not available'
        redirect_to root_url
      end
      format.json { render json: {:count => @count}}
    end

  end

  # GET /stitches/1
  # GET /stitches/1.json
  def show
    @stitch = Stitch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json #{ render json: @stitch }
    end
  end

  # GET /stitches/new
  # GET /stitches/new.json
  def new
    @stitch = Stitch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stitch }
    end
  end

  # GET /stitches/1/edit
  def edit
    @stitch = Stitch.find(params[:id])
  end

  # POST /stitches
  # POST /stitches.json
  def create
    @stitch = Stitch.new(params[:stitch])

    respond_to do |format|
      if @stitch.save
        format.html { redirect_to @stitch, notice: 'Stitch was successfully created.' }
        format.json { render json: @stitch, status: :created, location: @stitch }
      else
        format.html { render action: "new" }
        format.json { render json: @stitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stitches/1
  # PUT /stitches/1.json
  def update
    @stitch = Stitch.find(params[:id])

    respond_to do |format|
      if @stitch.update_attributes(params[:stitch])
        format.html { redirect_to @stitch, notice: 'Stitch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stitches/1
  # DELETE /stitches/1.json
  def destroy
    @stitch = Stitch.find(params[:id])
    @stitch.destroy

    respond_to do |format|
      format.html { redirect_to stitches_url }
      format.json { head :no_content }
    end
  end
end

app/views/stitches/_form.html.haml
= simple_form_for @stitch, :html => { :class => 'form-horizontal' } do |f|
  = f.input :year
  = f.input :season_code
  = f.input :machine_id
  = f.input :composition
  = f.input :brand_id
  = f.input :thinness
  = f.input :stretch
  = f.input :vanise
  = f.input :description
  = f.input :code
  = f.input :yarn_codes
  = f.input :product_codes
  = f.input :stitch_type_codes
  = f.input :stitch_type_id
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), stitches_path, :class => 'btn'

app/views/stitches/edit.html.haml
- model_class = Stitch
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stitches/index.html.haml
- model_class = Stitch
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

.span12
  .span11.offset1
    =link_to "archivia tutte le immagini", archive_stitches_path(:kind => "all_stitches"), :class => 'btn btn-warning', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_archive", :default => 'Confermi la generazione? Verranno archiviate tutte le immagini, rimosso l\'archivio delle immagini aggiornate e impostato a false l\'attributo updated_images')) }

    =link_to "Archivia immagini aggiornate", archive_stitches_path(:kind => "updated_stitches"), :class => 'btn btn-info', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_archive", :default => 'Confermi la generazione? Verranno archiviate solo le immagini per i punti con l\'attributo updated_images a true')) }

    =link_to "Testa caricamento Amazon S3", archive_stitches_path(:kind => "backup_test"), :class => 'btn btn-info', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_archive", :default => 'Verra\' effettuato un test di upload sui server Amazon. Procedere?')) }

    =link_to "Archivia immagini in Amazon S3", archive_stitches_path(:kind => "backup"), :class => 'btn btn-info', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_archive", :default => 'Attenzione l\'intero archivio verra caricato sui server di Amazon: la procedura potrebbe richiedere svariate ore. Procedere?')) }

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:code)
      %th= model_class.human_attribute_name(:year)
      %th= model_class.human_attribute_name(:composition)
      %th= model_class.human_attribute_name(:thinness)
      %th= model_class.human_attribute_name(:stretch)
      %th= model_class.human_attribute_name(:vanise)
      %th
        = model_class.human_attribute_name(:updated)
        %br
        = model_class.human_attribute_name(:images)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:pictures)
      %th= model_class.human_attribute_name(:stitch_type_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @stitches.each do |stitch|
      %tr
        %td= stitch.id
        %td= link_to stitch.code, stitch_path(stitch)
        %td= "#{stitch.year} / #{stitch.season_code}"
        %td= stitch.composition
        %td{:style =>"text-align:center;"}
          %span
            %strong
              = stitch.thinness
        %td
          -if stitch.stretch
            %span.icon-ok-circle{:title => "no", :style => "color:green;"}
          -else
            %span.icon-remove-circle{:title => "yes", :style => "color:orange;"}

        %td
          -if stitch.vanise
            %span.icon-ok-circle{:title => "no", :style => "color:green;"}
          -else
            %span.icon-remove-circle{:title => "yes", :style => "color:orange;"}

        %td
          -if stitch.updated_images
            %span.icon-ok-circle{:title => "no", :style => "color:green;"}
          -else
            %span.icon-remove-circle{:title => "yes", :style => "color:orange;"}


        %td= stitch.description

        %td
          =link_to "Visualizza", stitch_pictures_path({:stitch_id => stitch.id})
        %td
          -unless stitch.stitch_type.nil?
            =link_to stitch.stitch_type.description, stitch_type_path({:id => stitch.stitch_type_id})
          -else
            missing stitch_type
        %td=l stitch.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_stitch_path(stitch), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), stitch_path(stitch), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_stitch_path, :class => 'btn btn-primary'

=will_paginate @stitches, :renderer => BootstrapPagination::Rails, :class => 'pagination alternate'

app/views/stitches/new.html.haml
- model_class = Stitch
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stitches/show.html.haml
- model_class = Stitch
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:year) + ':'
  %br
  = @stitch.year
%p
  %strong= model_class.human_attribute_name(:season_code) + ':'
  %br
  = @stitch.season_code
%p
  %strong= model_class.human_attribute_name(:machine_id) + ':'
  %br
  = @stitch.machine_id
%p
  %strong= model_class.human_attribute_name(:composition) + ':'
  %br
  = @stitch.composition
%p
  %strong= model_class.human_attribute_name(:brand_id) + ':'
  %br
  = @stitch.brand_id
%p
  %strong= model_class.human_attribute_name(:thinness) + ':'
  %br
  = @stitch.thinness
%p
  %strong= model_class.human_attribute_name(:stretch) + ':'
  %br
  = @stitch.stretch
%p
  %strong= model_class.human_attribute_name(:vanise) + ':'
  %br
  = @stitch.vanise
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @stitch.description
%p
  %strong= model_class.human_attribute_name(:code) + ':'
  %br
  = @stitch.code
%p
  %strong= model_class.human_attribute_name(:yarn_codes) + ':'
  %br
  = @stitch.yarn_codes
%p
  %strong= model_class.human_attribute_name(:product_codes) + ':'
  %br
  = @stitch.product_codes
%p
  %strong= model_class.human_attribute_name(:stitch_type_codes) + ':'
  %br
  = @stitch.stitch_type_codes
%p
  %strong= model_class.human_attribute_name(:stitch_type_id) + ':'
  %br
  = @stitch.stitch_type_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), stitches_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_stitch_path(@stitch), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), stitch_path(@stitch), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'