config/routes.rb
Miles::Application.routes.draw do

  match "/queue" => DelayedJobWeb, :anchor => false

  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/i do

    get 'archives_count', as: :archive_count, :to => "stitches#archives_count"

    resources :brands do
      collection do
        get 'count'
      end
    end

    resources :stitch_type_products do
      collection do
        get 'count'
      end
    end

    resources :suppliers do
      collection do
        get 'count'
      end
    end

    resources :macro_seasons do
      collection do
        get 'count'
      end
    end

    resources :stitches do
      collection do
        get 'archive', as: :archive
        get 'count'
      end

      resources :pictures, :only => [:index, :show]

    end

    resources :pictures do
      collection do
        get 'download_url', :as => "download_archive"
        get 'export'
        get 'count'
      end
    end

    resources :stitch_products do
      collection do
        get 'count'
      end
    end

    resources :yarns do
      collection do
        get 'count'
      end
    end

    resources :products do
      collection do
        get 'count'
      end
    end

    resources :machines do
      collection do
        get 'count'
      end
    end

    resources :stitch_types do

      member do
        resources :stitch_type_products, :only => [:show, :index]
      end

      collection do
        get 'count'
        get 'tree'
      end
    end
    root :to => 'stitches#index'
  end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  match '*path', to: redirect {|params, request| "/#{I18n.default_locale}#{request.original_fullpath}"}, constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

end

app/controllers/stitch_types_controller.rb
class StitchTypesController < ApplicationController

  before_filter :set_pagination, :only => [:index]

  # GET /stitch_types
  # GET /stitch_types.json
  def index
    @stitch_types = StitchType.paginate(:page => @__page, :per_page => @__limit)
      .with_parent(params[:parent_id])
      .with_translations(Globalize.locale)
      .order("stitch_types.id ASC")
      .includes(:stitch_type_translations)

    respond_to do |format|
      format.html # index.html.erb
      format.json #{ render json: @stitch_types }
    end
  end

  def count
    @count = StitchType.count

    respond_to do |format|
      format.html do
        flash[:warning] = 'Not available'
        redirect_to root_url
      end
      format.json { render json: {:count => @count}}
    end

  end

  def tree

    @roots = StitchType.roots

    respond_to do |format|
      format.html { render "tree", :layout => "svg"}
    end

  end

  # GET /stitch_types/1
  # GET /stitch_types/1.json
  def show
    @stitch_type = StitchType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stitch_type }
    end
  end

  # GET /stitch_types/new
  # GET /stitch_types/new.json
  def new
    @stitch_type = StitchType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stitch_type }
    end
  end

  # GET /stitch_types/1/edit
  def edit
    @stitch_type = StitchType.find(params[:id])
  end

  # POST /stitch_types
  # POST /stitch_types.json
  def create
    @stitch_type = StitchType.new(params[:stitch_type])

    respond_to do |format|
      if @stitch_type.save
        format.html { redirect_to @stitch_type, notice: 'Stitch type was successfully created.' }
        format.json { render json: @stitch_type, status: :created, location: @stitch_type }
      else
        format.html { render action: "new" }
        format.json { render json: @stitch_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stitch_types/1
  # PUT /stitch_types/1.json
  def update
    @stitch_type = StitchType.find(params[:id])

    respond_to do |format|
      if @stitch_type.update_attributes(params[:stitch_type])
        format.html { redirect_to @stitch_type, notice: 'Stitch type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stitch_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stitch_types/1
  # DELETE /stitch_types/1.json
  def destroy
    @stitch_type = StitchType.find(params[:id])
    @stitch_type.destroy

    respond_to do |format|
      format.html { redirect_to stitch_types_url }
      format.json { head :no_content }
    end
  end
end

app/views/stitch_types/_form.html.haml
= simple_form_for @stitch_type, :html => { :class => 'form-horizontal' } do |f|
  = f.association :parent
  = f.input :code
  = f.input :leaf
  = f.input :description
  = f.input :full_description
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), stitch_types_path, :class => 'btn'

app/views/stitch_types/edit.html.haml
- model_class = StitchType
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stitch_types/index.html.haml
- model_class = StitchType
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:parent_id)
      %th= model_class.human_attribute_name(:code)
      %th= model_class.human_attribute_name(:leaf)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:stitches)
      %th= model_class.human_attribute_name(:extras)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @stitch_types.each do |stitch_type|
      %tr
        %td= link_to stitch_type.id, stitch_type_path(stitch_type)
        %td= stitch_type.parent_id
        %td= stitch_type.code
        %td= stitch_type.leaf
        %td= stitch_type.description
        %td
          -if stitch_type.stitches.count > 0
            =link_to "Stitches", stitches_path({:stitch_type_id => stitch_type.id})
          -else
            No stitch found
        %td
          -if stitch_type.has_children?
            =link_to "Childrens", stitch_types_path({:parent_id => stitch_type.id})
          -elsif stitch_type.has_products?
            =link_to "Stitch Type Products", stitch_type_products_path({:stitch_type_id => stitch_type.id})
        %td=l stitch_type.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_stitch_type_path(stitch_type), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), stitch_type_path(stitch_type), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

=will_paginate @stitch_types, :renderer => BootstrapPagination::Rails, :class => 'pagination alternate'

= link_to t('.new', :default => t("helpers.links.new")), new_stitch_type_path, :class => 'btn btn-primary'

app/views/stitch_types/new.html.haml
- model_class = StitchType
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stitch_types/show.html.haml
- model_class = StitchType
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:parent_id) + ':'
  %br
  = @stitch_type.parent_id
%p
  %strong= model_class.human_attribute_name(:code) + ':'
  %br
  = @stitch_type.code
%p
  %strong= model_class.human_attribute_name(:leaf) + ':'
  %br
  = @stitch_type.leaf
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @stitch_type.description
%p
  %strong= model_class.human_attribute_name(:full_description) + ':'
  %br
  = @stitch_type.full_description


.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), stitch_types_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_stitch_type_path(@stitch_type), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), stitch_type_path(@stitch_type), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/stitch_types/tree.html.haml
-@roots.each do |root|
  = tree_view(root)

app/views/stitch_types/tree_svg.html.erb
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.34.0 (20131130.1725)
 -->
<!-- Title: models_diagram Pages: 1 -->
<svg width="869pt" height="1064pt"
 viewBox="0.00 0.00 869.38 1064.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <% x = 25 %>
 <% y = 100 %>
 <% @roots.each do |root| -%>
 	<g id="<%=root.id %>" class="node">
 		<ellipse fill="none" stroke="#264e8b" cx="<%=(x+30)%>" cy="<%=(y) %>" rx="50" ry="25"/>
 		<title>_diagram_info</title>
		<text text-anchor="start" x="<%=x %>" y="<%= y%>" font-family="Times,serif" font-size="13.00"><%=root.description %></text>
	</g>
	<% y +=60 %>
 <% end -%>
</svg>