config/routes.rb
Miles::Application.routes.draw do

  match "/queue" => DelayedJobWeb, :anchor => false

  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/i do

    get 'archives_count', as: :archive_count, :to => "stitches#archives_count"

    resources :brands do
      collection do
        get 'count'
      end
    end

    resources :stitch_type_products do
      collection do
        get 'count'
      end
    end

    resources :suppliers do
      collection do
        get 'count'
      end
    end

    resources :macro_seasons do
      collection do
        get 'count'
      end
    end

    resources :stitches do
      collection do
        get 'archive', as: :archive
        get 'count'
      end

      resources :pictures, :only => [:index, :show]

    end

    resources :pictures do
      collection do
        get 'download_url', :as => "download_archive"
        get 'export'
        get 'count'
      end
    end

    resources :stitch_products do
      collection do
        get 'count'
      end
    end

    resources :yarns do
      collection do
        get 'count'
      end
    end

    resources :products do
      collection do
        get 'count'
      end
    end

    resources :machines do
      collection do
        get 'count'
      end
    end

    resources :stitch_types do

      member do
        resources :stitch_type_products, :only => [:show, :index]
      end

      collection do
        get 'count'
        get 'tree'
      end
    end
    root :to => 'stitches#index'
  end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  match '*path', to: redirect {|params, request| "/#{I18n.default_locale}#{request.original_fullpath}"}, constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

end

app/models/picture.rb
class Picture < I18nModel
  attr_accessible :description, :stitch_id, :image, :code

  belongs_to :stitch

  has_attached_file :image,
      :path => ":rails_root/public/system/:attachment/:style/:id.:extension",
      :url => "/system/:attachment/:style/:id.:extension",
      :styles =>{
        :original => {:geometry =>"100%", :format => :jpg, :density => 72, :processor => [:screen_density]},
        :medium => {:geometry => "584^x584", :format => :jpg, :density => 72, :processor => [:screen_density]}
      }
      #584
      #:thumb => ["200^x200", :jpg]

  #validates_attachment :image, :presence => true,
  #  :content_type => { :content_type => ["image/jpg","image/png"] },
  #  :size => { :in => 0..10.kilobytes }

  def self.for_code(code)
    self.all(:conditions => {:code => code})
  end

  scope :updated , lambda{
      {:joins => [:stitch], :conditions => ["stitches.updated_images = ?",true]}
  }

  scope :for_stitch , lambda{ |stitch_id|
    if stitch_id.blank?
      {}
    else
      {:conditions => ["pictures.stitch_id = ?",stitch_id.to_i]}
    end
  }

  def self.with_code(code)
    self.all(:conditions => {:code => code}, :limit => 1).first
  end

  def updated?
    self.stitch.updated_images
  end

  def self.s3_archive_url

    s3 = AWS::S3.new(
        :access_key_id => self.s3_config['access_key_id'],
        :secret_access_key => self.s3_config['secret_access_key']
      )

    bucket = s3.buckets['bluetouchdev-backups']
    obj = bucket.objects['miles/images/images.zip']
    url = obj.url_for(:read, :expire => 10 * 60)

    url
  end

  def self.import(stitch_code, base_path)
    import_from_stitch nil, stitch_code, base_path
  end
  def self.import_from_stitch(stitch, stitch_code, base_path)
    stitch = Stitch.with_code(stitch_code.to_s) if stitch.nil?
    pictures = Picture.find_all_by_code(stitch_code.to_s)


    unless stitch.nil?
      Delayed::Worker.logger.debug("Stitch #{stitch_code} found")
      unless pictures.nil?
        pictures.each{|p| p.destroy}
      end
      stitch_code = stitch.code
      Delayed::Worker.logger.debug("Base path. #{base_path}/#{stitch_code.to_s}.*)")
      #immagine normale
      Dir.glob(File.join(base_path, "/#{stitch_code.to_s}.*")) do |file_path|
        puts "---> Going to import #{file_path} for stitch with id #{stitch.id}\n"

        # create new model for every picture found and save it to db
        open(file_path) do |f|
          pict = Picture.new(:stitch_id => stitch.id, :description => File.basename(file_path),
                             :image => f, :code => stitch_code.to_s)
          pict.save!
        end
      end

      Delayed::Worker.logger.debug("Base path. #{base_path}/#{stitch_code.to_s}_Dettaglio.*)")
      #Dettaglio
      Dir.glob(File.join(base_path, "/#{stitch_code.to_s}_Dettaglio.*")) do |file_path|
        puts "---> Going to import #{file_path} for stitch with id #{stitch.id}\n"

        # create new model for every picture found and save it to db
        open(file_path) do |f|
          pict = Picture.new(:stitch_id => stitch.id, :description => File.basename(file_path),
                             :image => f, :code => stitch_code.to_s)
          pict.save!
        end
      end

      Delayed::Worker.logger.debug("Base path. #{base_path}/#{stitch_code.to_s}_dettaglio.*)")
      #dettaglio
      Dir.glob(File.join(base_path, "/#{stitch_code.to_s}_dettaglio.*")) do |file_path|
        puts "---> Going to import #{file_path} for stitch with id #{stitch.id}\n"

        # create new model for every picture found and save it to db
        open(file_path) do |f|
          pict = Picture.new(:stitch_id => stitch.id, :description => File.basename(file_path),
                             :image => f, :code => stitch_code.to_s)
          pict.save!
        end
      end


    else
      puts "---> Invalid / missing stitch \n"
    end

  end

  def self.fix
    Picture.find_each do |p|
      unless p.stitch.nil?
        puts "Updating code to #{p.stitch.code} for picture #{p.id}"
        p.code = p.stitch.code
        p.save!
      else
        puts "Missing stitch for picture #{p.id}"
      end
    end
  end

  def self.reconnect(stitch_code)

    stitch = Stitch.with_code(stitch_code.to_s)
    pictures = Picture.for_code(stitch_code.to_s)

    unless stitch.nil?
      pictures.each do |p|
        #puts "Reconnecting picture #{p.id} to stitch #{stitch.code} - #{stitch.id}"
        p.stitch_id = stitch.id
        p.save!
      end
    end

  end

  protected

  def self.s3_config
    @@s3_config ||= YAML.load(ERB.new(File.read("#{Rails.root}/config/s3.yml")).result)[Rails.env]
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController


  before_filter :set_pagination, :only => [:index]


  def download_url

    s3_config ||= YAML.load(ERB.new(File.read("#{Rails.root}/config/s3.yml")).result)[Rails.env]

    s3 = AWS::S3.new(
        :access_key_id => s3_config['access_key_id'],
        :secret_access_key => s3_config['secret_access_key']
      )

    bucket = s3.buckets['bluetouchdev-backups']
    obj = bucket.objects['miles/images/images.zip']
    @url = obj.url_for(:read, :expire => 10 * 60)

    respond_to do |format|
      format.json {render json:{:secure_url => Picture.s3_archive_url.to_s}, status: :ok}
      format.html {redirect_to Picture.s3_archive_url.to_s}
    end
  end


  # GET /pictures/export.json
  def export
    

    respond_to do |format|
      format.html do
        flash[:notice] = "Not available"
        redirect_to root_url
      end
      format.json do
        @pictures = Picture.order("id ASC").all
        render json: @pictures
      end
    end
  end

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.paginate(:page => @__page, :per_page => @__limit)
      .for_stitch(params[:stitch_id])
      .order(request.format == 'json' ? "id ASC" : 'code ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  def count
    @count = Picture.count

    respond_to do |format|
      format.html do
        flash[:warning] = 'Not available'
        redirect_to root_url
      end
      format.json { render json: {:count => @count}}
    end

  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end 
end

app/views/pictures/_form.html.haml
= simple_form_for @picture, :html => { :class => 'form-horizontal' } do |f|
  = f.input :description
  = f.association :stitch
  = f.input :image
  .form-actions
    = f.button :submit, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), pictures_path, :class => 'btn'

app/views/pictures/edit.html.haml
- model_class = Picture
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/pictures/index.html.haml
- model_class = Picture
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

=link_to "Scarica archivio da amazon S3", download_archive_pictures_path(:kind => "all"), :class => 'btn btn-info'

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:thumb)
      %th= model_class.human_attribute_name(:stitch_id)
      %th= model_class.human_attribute_name(:image_file_name)
      %th= model_class.human_attribute_name(:image_content_type)
      %th= model_class.human_attribute_name(:image_file_size)
      %th= model_class.human_attribute_name(:image_updated_at)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @pictures.each do |picture|
      %tr
        %td= link_to picture.id, picture_path(picture)
        %td
          =image_tag picture.image.url(:medium), :style => "height:30px;"
        %td= picture.stitch_id
        %td= picture.image_file_name
        %td= picture.image_content_type
        %td= picture.image_file_size
        %td= picture.image_updated_at
        %td=l picture.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_picture_path(picture), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), picture_path(picture), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

=will_paginate @pictures, :renderer => BootstrapPagination::Rails, :class => 'pagination alternate'

= link_to t('.new', :default => t("helpers.links.new")), new_picture_path, :class => 'btn btn-primary'

app/views/pictures/new.html.haml
- model_class = Picture
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/pictures/show.html.haml
- model_class = Picture
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @picture.description
%p
  %strong= model_class.human_attribute_name(:stitch_id) + ':'
  %br
  = @picture.stitch_id
%p
  %strong= model_class.human_attribute_name(:image) + ':'
  %br
  =image_tag @picture.image.url(:medium)

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), pictures_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_picture_path(@picture), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), picture_path(@picture), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'