config/routes.rb
Miles::Application.routes.draw do

  match "/queue" => DelayedJobWeb, :anchor => false

  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/i do

    get 'archives_count', as: :archive_count, :to => "stitches#archives_count"

    resources :brands do
      collection do
        get 'count'
      end
    end

    resources :stitch_type_products do
      collection do
        get 'count'
      end
    end

    resources :suppliers do
      collection do
        get 'count'
      end
    end

    resources :macro_seasons do
      collection do
        get 'count'
      end
    end

    resources :stitches do
      collection do
        get 'archive', as: :archive
        get 'count'
      end

      resources :pictures, :only => [:index, :show]

    end

    resources :pictures do
      collection do
        get 'download_url', :as => "download_archive"
        get 'export'
        get 'count'
      end
    end

    resources :stitch_products do
      collection do
        get 'count'
      end
    end

    resources :yarns do
      collection do
        get 'count'
      end
    end

    resources :products do
      collection do
        get 'count'
      end
    end

    resources :machines do
      collection do
        get 'count'
      end
    end

    resources :stitch_types do

      member do
        resources :stitch_type_products, :only => [:show, :index]
      end

      collection do
        get 'count'
        get 'tree'
      end
    end
    root :to => 'stitches#index'
  end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  match '*path', to: redirect {|params, request| "/#{I18n.default_locale}#{request.original_fullpath}"}, constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

end

app/models/stitch_type_product.rb
class StitchTypeProduct < I18nModel
  attr_accessible :brand, :category, :description, :model, :product_code
  attr_accessible :product_id, :season, :stitch_type_code, :stitch_type_id, :year
  attr_accessible :updated_picture, :updated_sketch

  attr_accessible :image, :sketch

  belongs_to :product
  belongs_to :stitch_type

  scope :with_stitch_type_id , lambda{ |stitch_type_id|
    if stitch_type_id.blank?
      {}
    else
      {:conditions => ["stitch_type_products.stitch_type_id = ?",stitch_type_id.to_i]}
    end
  }

  has_attached_file :image,
      :path => ":rails_root/public/system/products/:attachment/:style/:id.:extension",
      :url => "/system/products/:attachment/:style/:id.:extension",
      :styles =>{
        :original => {:geometry =>"100%", :format => :jpg, :density => 72, :processor => [:screen_density]},
        :medium => {:geometry => "500^x750", :format => :jpg, :density => 72, :processor => [:screen_density]}
      }


  has_attached_file :sketch,
      :path => ":rails_root/public/system/products/:attachment/:style/:id.:extension",
      :url => "/system/products/:attachment/:style/:id.:extension"

  def self.s3_archive_url

    s3 = AWS::S3.new(
        :access_key_id => self.s3_config['access_key_id'],
        :secret_access_key => self.s3_config['secret_access_key']
      )

    bucket = s3.buckets['bluetouchdev-backups']
    obj = bucket.objects['miles/images/images.zip']
    url = obj.url_for(:read, :expire => 10 * 60)

    url
  end

  def self.with_stitch_type_and_product_code(s_code,p_code)
    self.all(:conditions => {:stitch_type_code => s_code, :product_code => p_code}, :limit => 1).first
  end

  def self.find_or_initialize_by_stitch_type_and_product_code(s_code,p_code)
  	x = with_stitch_type_and_product_code(s_code,p_code)
  	x = StitchTypeProduct.new({:stitch_type_code => s_code, :product_code => p_code}) if x.nil?
  	x
  end


  #picture import management

  def import_images

    stitch_type = StitchType.with_code(self.stitch_type_code.to_s)
    puts "Importing / updating images for product #{self.product_code} (stitch type #{stitch_type.id})"

    unless stitch_type.nil?

      if self.updated_picture
        #immagine normale
        Dir.glob(File.join(picture_base_path, "/#{self.product_code.to_s.downcase}.jpg")) do |file_path|
          puts "---> Going to import product image #{file_path} for product #{self.id}\n"

          # create new model for every picture found and save it to db
          open(file_path) do |f|
            self.image = f
            self.save!
          end
        end
      else
        puts "Picture not updated, keeping current version"
      end

      if self.updated_sketch
        #sketch
        Dir.glob(File.join(sketch_base_path, "/#{self.product_code.to_s.upcase}.JPG")) do |file_path|
          puts "---> Going to import product sketch #{file_path} for product #{self.id}\n"

          # create new model for every picture found and save it to db
          open(file_path) do |f|
            self.sketch = f
            self.save!
          end
        end
      else
        puts "Sketch not updated, keeping current version"
      end

    else
      puts "---> Invalid missing stitch type\n"
    end

  end

  private

  def sketch_base_path
    Rails.env == 'production' ? "/media/milnas/Schizzi/" : "#{Rails.root}/config/import/Schizzi"
  end

  def picture_base_path
    Rails.env == 'production' ? "/media/milnas/Foto/" : "#{Rails.root}/config/import/Foto"
  end

end

app/controllers/stitch_type_products_controller.rb
class StitchTypeProductsController < ApplicationController

	before_filter :set_pagination, :only => [:index]

  # GET /stitch_type_products
  # GET /stitch_type_products.json
  def index
    @stitch_type_products = StitchTypeProduct.paginate(:page => @__page, :per_page => @__limit)
      .with_stitch_type_id(params[:stitch_type_id])
      .order("id ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json #{ render json: @stitch_type_products }
    end
  end

  def count
    @count = StitchTypeProduct.count

    respond_to do |format|
      format.html do
        flash[:warning] = 'Not available'
        redirect_to root_url
      end
      format.json { render json: {:count => @count}}
    end

  end

  # GET /stitch_type_products/1
  # GET /stitch_type_products/1.json
  def show
    @stitch_type_product = StitchTypeProduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stitch_type_product }
    end
  end

  # GET /stitch_type_products/new
  # GET /stitch_type_products/new.json
  def new
    @stitch_type_product = StitchTypeProduct.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stitch_type_product }
    end
  end

  # GET /stitch_type_products/1/edit
  def edit
    @stitch_type_product = StitchTypeProduct.find(params[:id])
  end

  # POST /stitch_type_products
  # POST /stitch_type_products.json
  def create
    @stitch_type_product = StitchTypeProduct.new(params[:stitch_type_product])

    respond_to do |format|
      if @stitch_type_product.save
        format.html { redirect_to @stitch_type_product, notice: 'Stitch type product was successfully created.' }
        format.json { render json: @stitch_type_product, status: :created, location: @stitch_type_product }
      else
        format.html { render action: "new" }
        format.json { render json: @stitch_type_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stitch_type_products/1
  # PUT /stitch_type_products/1.json
  def update
    @stitch_type_product = StitchTypeProduct.find(params[:id])

    respond_to do |format|
      if @stitch_type_product.update_attributes(params[:stitch_type_product])
        format.html { redirect_to @stitch_type_product, notice: 'Stitch type product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stitch_type_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stitch_type_products/1
  # DELETE /stitch_type_products/1.json
  def destroy
    @stitch_type_product = StitchTypeProduct.find(params[:id])
    @stitch_type_product.destroy

    respond_to do |format|
      format.html { redirect_to stitch_type_products_url }
      format.json { head :no_content }
    end
  end


end

app/views/stitch_type_products/_form.html.haml
= simple_form_for @stitch_type_product, :html => { :class => 'form-horizontal' } do |f|
  = f.input :stitch_type_code
  = f.input :stitch_type_id
  = f.input :product_code
  = f.input :product_id
  = f.input :description
  = f.input :category
  = f.input :year
  = f.input :season
  = f.input :brand
  = f.input :model
  = f.input :updated_picture
  = f.input :updated_sketch
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), stitch_type_products_path, :class => 'btn'

app/views/stitch_type_products/edit.html.haml
- model_class = StitchTypeProduct
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stitch_type_products/index.html.haml
- model_class = StitchTypeProduct
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

.span12
  .span11.offset1
    =link_to "archivia tutte le immagini", archive_stitches_path(:kind => "all_products_images"), :class => 'btn btn-warning', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_archive", :default => 'Confermi la generazione? Verranno archiviate tutte le immagini, rimosso l\'archivio delle immagini aggiornate e impostato a false l\'attributo updated_picture')) }

    =link_to "archivia tutti i bozzetti", archive_stitches_path(:kind => "all_products_sketches"), :class => 'btn btn-warning', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_archive", :default => 'Confermi la generazione? Verranno archiviate tutte le immagini, rimosso l\'archivio dei bozzetti aggiornati e impostato a false l\'attributo updated_sketch')) }

    =link_to "Archivia immagini aggiornate", archive_stitches_path(:kind => "updated_products_images"), :class => 'btn btn-info', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_archive", :default => 'Confermi la generazione? Verranno archiviate solo le immagini per i prodotti con l\'attributo updated_picture a true')) }

    =link_to "Archivia immagini bozzetti aggiornate", archive_stitches_path(:kind => "updated_products_sketches"), :class => 'btn btn-info', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_archive", :default => 'Confermi la generazione? Verranno archiviate solo le immagini dei bozzetti per i prodotti con l\'attributo updated_sketch a true')) }

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th
        = model_class.human_attribute_name(:stitch)
        %br
        = model_class.human_attribute_name(:type)
        %br
        = model_class.human_attribute_name(:code)

        
      %th= model_class.human_attribute_name(:product_code)
      %th= model_class.human_attribute_name(:stitch_type)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:year)
      %th= model_class.human_attribute_name(:season)
      %th= model_class.human_attribute_name(:brand)
      %th= model_class.human_attribute_name(:sketch)
      %th= model_class.human_attribute_name(:image)
      %th
 
        = model_class.human_attribute_name(:updated)
        %br
        = model_class.human_attribute_name(:sketch)

      %th
 
        = model_class.human_attribute_name(:updated)
        %br
        = model_class.human_attribute_name(:picture)

      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @stitch_type_products.each do |stitch_type_product|
      %tr
        %td= stitch_type_product.id
        %td= stitch_type_product.stitch_type_code
        %td= link_to stitch_type_product.product_code, stitch_type_product_path(stitch_type_product)
        %td
          -unless stitch_type_product.stitch_type.nil?
            = stitch_type_product.stitch_type.description
        %td= stitch_type_product.description
        %td= stitch_type_product.year
        %td= stitch_type_product.season
        %td= stitch_type_product.brand
        %td
          -unless stitch_type_product.sketch_file_name.nil?
            =link_to image_tag(stitch_type_product.sketch.url(:original), :style => "height:30px;"), stitch_type_product.sketch.url(:original), :target =>  "_blank"
        %td
          -unless stitch_type_product.image_file_name.nil?
            =link_to image_tag(stitch_type_product.image.url(:medium), :style => "height:30px;"),stitch_type_product.image.url(:medium), :target =>  "_blank"

        %td
          -if stitch_type_product.updated_sketch
            %span.icon-ok-circle{:title => "no", :style => "color:green;"}
          -else
            %span.icon-remove-circle{:title => "yes", :style => "color:orange;"}

        %td
          -if stitch_type_product.updated_picture
            %span.icon-ok-circle{:title => "no", :style => "color:green;"}
          -else
            %span.icon-remove-circle{:title => "yes", :style => "color:orange;"}
        
        %td=l stitch_type_product.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_stitch_type_product_path(stitch_type_product), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), stitch_type_product_path(stitch_type_product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

=will_paginate @stitch_type_products, :renderer => BootstrapPagination::Rails, :class => 'pagination alternate'

= link_to t('.new', :default => t("helpers.links.new")), new_stitch_type_product_path, :class => 'btn btn-primary'

app/views/stitch_type_products/new.html.haml
- model_class = StitchTypeProduct
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stitch_type_products/show.html.haml
- model_class = StitchTypeProduct
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

.row-fluid
  .span6
    %p
      %strong
        = model_class.human_attribute_name(:stitch)
        %br
        = model_class.human_attribute_name(:type)
        %br
        = model_class.human_attribute_name(:code) + ':'
      %br
      = @stitch_type_product.stitch_type_code
    %p
      %strong= model_class.human_attribute_name(:stitch_type_id) + ':'
      %br
      = @stitch_type_product.stitch_type_id
    %p
      %strong= model_class.human_attribute_name(:product_code) + ':'
      %br
      = @stitch_type_product.product_code
    %p
      %strong= model_class.human_attribute_name(:product_id) + ':'
      %br
      = @stitch_type_product.product_id
    %p
      %strong= model_class.human_attribute_name(:description) + ':'
      %br
      = @stitch_type_product.description
    %p
      %strong= model_class.human_attribute_name(:category) + ':'
      %br
      = @stitch_type_product.category
    %p
      %strong= model_class.human_attribute_name(:year) + ':'
      %br
      = @stitch_type_product.year
    %p
      %strong= model_class.human_attribute_name(:season) + ':'
      %br
      = @stitch_type_product.season
    %p
      %strong= model_class.human_attribute_name(:brand) + ':'
      %br
      = @stitch_type_product.brand
    %p
      %strong= model_class.human_attribute_name(:model) + ':'
      %br
      = @stitch_type_product.model
    %p
      %strong= model_class.human_attribute_name(:updated_picture) + ':'
      -if @stitch_type_product.updated_picture
        %span.icon-ok-circle{:title => "no", :style => "color:green;font-size:25px;"}
      -else
        %span.icon-remove-circle{:title => "yes", :style => "color:orange;font-size:25px;"}

    %p
      %strong= model_class.human_attribute_name(:updated_sketch) + ':'
      -if @stitch_type_product.updated_sketch
        %span.icon-ok-circle{:title => "no", :style => "color:green;font-size:25px;"}
      -else
        %span.icon-remove-circle{:title => "yes", :style => "color:orange;font-size:25px;"}

  .span6
    %div
      %h3 Sketch image
      -unless @stitch_type_product.sketch_file_name.nil?
        =image_tag(@stitch_type_product.sketch.url(:original), :style => "height:200px;")
    %div
      %h3 Sketch image
      -unless @stitch_type_product.image_file_name.nil?
        =link_to image_tag(@stitch_type_product.image.url(:medium), :style => "height:200px;"), @stitch_type_product.image.url(:original)

.row-fluid
  .span12
    .form-actions
      = link_to t('.back', :default => t("helpers.links.back")), stitch_type_products_path, :class => 'btn'
      = link_to t('.edit', :default => t("helpers.links.edit")), edit_stitch_type_product_path(@stitch_type_product), :class => 'btn'
      = link_to t('.destroy', :default => t("helpers.links.destroy")), stitch_type_product_path(@stitch_type_product), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'